name: Build HTML documentation
on:
  workflow_call:
    inputs:
      submodules:
        description: 'Whether to checkout submodules'
        default: false
        type: boolean
      upload:
        description: 'Whether to upload an archive of the documentation'
        default: false
        type: boolean
      artifact-name:
        description: 'Artifact name to use for the uploaded documentation'
        default: docs
        type: string
      artifact-retention-days:
        description: 'Number of days after which the artifact will expire'
        default: 1
        type: number
      deploy:
        description: 'Whether to deploy the documentation'
        default: false
        type: boolean
      project:
        description: 'Project name for the deployment'
        type: string
      version:
        description: 'Project version for the deployment'
        type: string

permissions: {}

jobs:
  build:
    runs-on: ${{ matrix.os }}
    # If deployment is enabled, ignore errors in jobs that are not required for deploying
    continue-on-error: ${{ inputs.deploy && !matrix.upload }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-12, ubuntu-22.04]
        include:
          - os: ubuntu-22.04
            upload: ${{ inputs.upload || inputs.deploy }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: ${{ !matrix.upload && 1 || 0 }}
          submodules: ${{ inputs.submodules }}
          show-progress: false
      - name: Fix tag
        # Workaround actions/checkout bug
        # https://github.com/actions/checkout/issues/290
        # https://github.com/actions/checkout/issues/882
        if: github.ref_type == 'tag'
        run: git fetch -fv origin tag "${GITHUB_REF_NAME}"
      - name: Install dependencies
        run: |
          find .jenkins.d/ -type f -name '[1-9]*.sh' -exec chmod -x '{}' +
          ./.jenkins
        env:
          CACHE_DIR: ${{ runner.temp }}
          JOB_NAME: Docs
      - name: Prepare environment
        run: python3 -c 'import sysconfig; print(sysconfig.get_path("scripts", "posix_user"))' >> $GITHUB_PATH
      - name: Build HTML documentation
        run: |
          ./waf --color=yes configure
          ./waf --color=yes build --targets=version.hpp || true
          ./waf --color=yes docs
      - name: Create archive
        if: matrix.upload
        run: |
          rm -rf build/docs/{.buildinfo,.doctrees,Doxyfile,doxygen.conf}
          tar -caf docs.tar.zst -C build/docs .
      - name: Upload archive
        if: matrix.upload
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
          path: docs.tar.zst
          retention-days: ${{ inputs.artifact-retention-days }}

  deploy:
    if: inputs.deploy
    needs: build
    uses: ./.github/workflows/docs-deployment.yml
    with:
      project: ${{ inputs.project }}
      version: ${{ inputs.version }}
      artifact-name: ${{ inputs.artifact-name }}
    secrets: inherit
