name: Deploy documentation
on:
  workflow_call:
    inputs:
      project:
        description: >
          Project name. By default, this is derived from `$GITHUB_REPOSITORY`.
        type: string
      version:
        description: >
          Project version. By default, this is derived from `$GITHUB_REF_NAME`.
        type: string
      artifact-name:
        description: >
          Name of the artifact containing the files to deploy. Any top-level tarballs
          in the artifact are automatically extracted. Either `artifact-name` or
          `artifact-id` can be used, but not both.
        type: string
      artifact-id:
        description: >
          ID of the artifact containing the files to deploy. Any top-level tarballs
          in the artifact are automatically extracted. Either `artifact-name` or
          `artifact-id` can be used, but not both.
        type: string

permissions: {}

jobs:
  deploy:
    if: vars.DOCS_DEPLOYMENT_HOST != ''
    runs-on: ubuntu-latest
    concurrency: docs
    environment:
      name: docs
      url: https://${{ vars.DOCS_DEPLOYMENT_HOST }}/${{ steps.metadata.outputs.slug }}/
    steps:
      - name: Determine project name and version
        id: metadata
        env:
          PN: ${{ inputs.project }}
          PV: ${{ inputs.version }}
        run: |
          if [[ -z ${PN} ]]; then
            PN=${GITHUB_REPOSITORY#*/}
          fi
          if [[ -z ${PV} ]]; then
            PV=${GITHUB_REF_NAME#"${PN}"-}
            PV=${PV#v}
          fi
          tee -a "$GITHUB_OUTPUT" <<EOF
          name=${PN}
          version=${PV}
          slug=${PN}/${PV}
          EOF
      - name: Download archive
        uses: actions/download-artifact@v5
        with:
          name: ${{ inputs.artifact-name }}
          artifact-ids: ${{ inputs.artifact-id }}
      - name: Extract archive
        run: find . -maxdepth 1 -type f -name '*.tar.*' -printf '%P\n' -exec tar -xf '{}' \; -delete
      - name: Deploy to ${{ vars.DOCS_DEPLOYMENT_HOST }}
        uses: easingthemes/ssh-deploy@a1aa0b6cf96ce2406eef90faa35007a4a7bf0ac0 # v5.1.1
        with:
          ARGS: -chirvzEW --delay-updates --delete-delay
          REMOTE_HOST: ${{ vars.DOCS_DEPLOYMENT_HOST }}
          REMOTE_PORT: ${{ secrets.DOCS_DEPLOYMENT_PORT }}
          REMOTE_USER: ${{ secrets.DOCS_DEPLOYMENT_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.DOCS_DEPLOYMENT_SSH_KEY }}
          SOURCE: ./
          TARGET: /srv/docs/${{ steps.metadata.outputs.slug }}/
