name: Run .jenkins script (Ubuntu)
on:
  workflow_call:
    inputs:
      submodules:
        description: 'Whether to checkout submodules'
        default: false
        required: false
        type: boolean

permissions: {}

jobs:
  build:
    name: ${{ matrix.compiler }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - {os: ubuntu-20.04, compiler: g++-7}
          - {os: ubuntu-20.04, compiler: g++-8}
          - {os: ubuntu-20.04, compiler: g++-9}
          - {os: ubuntu-22.04, compiler: g++-10}
          - {os: ubuntu-22.04, compiler: g++-11}
          - {os: ubuntu-22.04, compiler: g++-12}
          - {os: ubuntu-20.04, compiler: clang++-7}
          - {os: ubuntu-20.04, compiler: clang++-8}
          - {os: ubuntu-20.04, compiler: clang++-9}
          - {os: ubuntu-20.04, compiler: clang++-10}
          - {os: ubuntu-20.04, compiler: clang++-11}
          - {os: ubuntu-22.04, compiler: clang++-12}
          - {os: ubuntu-22.04, compiler: clang++-13}
          - {os: ubuntu-22.04, compiler: clang++-14}
    env:
      CXX: ${{ matrix.compiler }}
    steps:
      - name: Install C++ compiler
        run: |
          sudo apt-get -qy install ${CXX/clang++/clang}
          ${CXX} --version
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: ${{ inputs.submodules }}
      - name: Build and test
        run: ./.jenkins
        env:
          CACHE_DIR: ${{ runner.temp }}
