name: Lint
on:
  push:
    branches:
      - '**'
  pull_request:
  workflow_dispatch:

permissions:
  checks: write

jobs:
  actionlint:
    # Cannot run on ubuntu-slim because reviewdog/action-actionlint requires docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          persist-credentials: false
          show-progress: false
      - name: Run actionlint
        uses: reviewdog/action-actionlint@320fcdd9c860767cf17fab3b20e22e739d5d02b8 # v1.76.0
        with:
          reporter: github-check
        env:
          SHELLCHECK_OPTS: "-o avoid-nullary-conditions,deprecate-which,require-double-brackets"
