name: Lint
on:
  push:
    branches:
      - '**'
  pull_request:
  workflow_dispatch:

permissions:
  checks: write

jobs:
  actionlint:
    # Cannot run on ubuntu-slim because reviewdog/action-actionlint requires docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          persist-credentials: false
          show-progress: false
      - name: Run actionlint
        uses: reviewdog/action-actionlint@50842263c20a7c46bd0065b9e624d3c569db061e # v1.73.0
        with:
          reporter: github-check
        env:
          SHELLCHECK_OPTS: "-o avoid-nullary-conditions,deprecate-which,require-double-brackets"
