name: Build against PPA packages
run-name: Build ${{ inputs.repository }} against PPA

on:
  workflow_call:
    inputs:
      extra-deps:
        description: >
          Space-separated list of APT packages to install as additional build
          dependencies, if any. libndn-cxx-dev and its dependencies are always
          installed. libboost-test-dev is automatically installed when building
          with unit tests enabled.
        type: string
      submodules:
        description: 'Whether to checkout submodules'
        default: false
        type: boolean
  workflow_dispatch:
    inputs:
      repository:
        description: 'Full name of the repository on which to run the workflow'
        default: named-data/
        required: true
        type: string
      extra-deps:
        description: 'Additional APT packages to install'
        type: string
      submodules:
        description: 'Checkout submodules?'
        default: false
        type: boolean

permissions: {}

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository || github.repository }}
          submodules: ${{ inputs.submodules }}
          show-progress: false
      - name: Install dependencies
        env:
          EXTRA_DEPS: ${{ inputs.extra-deps }}
        run: |
          sudo apt-get -qy install software-properties-common
          sudo add-apt-repository -uy ppa:named-data/ppa
          sudo apt-get -qy install --no-install-recommends libndn-cxx-dev ${EXTRA_DEPS}
      - name: Release build
        run: |
          ARGS=()
          if ./waf configure --help | grep -Fw -- --with-examples >/dev/null; then
            ARGS+=(--with-examples)
          fi
          set -x
          ./waf --color=yes distclean
          ./waf --color=yes configure "${ARGS[@]}"
          ./waf --color=yes build
      - name: Debug build
        run: |
          ARGS=(--debug)
          if ./waf configure --help | grep -Fw -- --with-tests >/dev/null; then
            ARGS+=(--with-tests)
            sudo apt-get -qy install --no-install-recommends libboost-test-dev
          fi
          set -x
          ./waf --color=yes distclean
          ./waf --color=yes configure "${ARGS[@]}"
          ./waf --color=yes build
